### ISSUE TITLE
Erro ao tentar utilizar após instalação

### ISSUE THREAD

**Issue by leandrosimoes** [theuves/dicio#10]
Após instalação pelo npm, rodei o comando `dicio teste` e apareceu o seguinte erro:

![error](https://drive.google.com/uc?export=view&id=1F0tA-OEsKnKzGVX3CF-16S_mFqjBxxba)

Creio que adicionando o package `request` como dependência no `package.json` que irá resolver.

**Comment by theuves** [comment]
Obrigado, @leandrosimoes!

Corrigido na versão 0.4.3!!!

😄
