### ISSUE TITLE
class modificada no site

### ISSUE THREAD

**Issue by evandojunior** [theuves/dicio#6]
Olá, fiz a instalação do dicio e notei que não estava funcionando, verifiquei os arquivos e notei que está utilizando essa class como parametro:

```
.split('<h3 itemprop="description">\n')[1] // 1
            .split('</h3>')[0] // 2
            .replace(/<br>/g, '') // 3
.replace(/:\s+/gi, ': '); // 4
```

Porém no site https://dicionariodoaurelio.com, está com a class 
``` 
headline 
```

**Comment by theuves** [comment]
Eita, obrigado.

Percebi que você corrigiu o erro no *fork* que fez.

Poderia enviar um *Pull Request* dele?

**Comment by evandojunior** [comment]
Pull Request realizado :)

**Comment by theuves** [comment]
Obrigado!
