### ISSUE TITLE
Estilizar o output

### ISSUE THREAD

**Issue by theuves** [theuves/dicio#9]
Adicionar cores e formatar corretamente a definição apresentada.

**Comment by nolleto** [comment]
Criei uma PR que da uma estilizada, olhe e veja se ficou bom, senão modificamos pra ficar melhor.

Na versão q eu fiz eu reparei que em alguns casos pode vir bastante conteúdo, e isso pode deixar menos `clean` o output gerado. Talvez seja interessante adicionar uma config para o usuário escolher quando quer todo conteúdo ou não.

Exemplo:
- `$ dicio correr` -> exibe somente as definições
- `$ dicio correr -d` -> exibe tudo, definições, sinônimos, antônimos...

**Comment by theuves** [comment]
Adicionei as opções para acessar cada dado separadamente ou tudo de uma vez.

Veja mais informações no README.

Muito obrigado.
